//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sushkov_LabSession.LabDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> OrderedServiceID { get; set; }
        public Nullable<int> InsuranceCompID { get; set; }
    
        public virtual InsuranceComp InsuranceComp { get; set; }
        public virtual OrderedService OrderedService { get; set; }
        public virtual Users Users { get; set; }
    }
}
